# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /media/data/Unreal Engine/Linux_Unreal_Engine_5.1.1
GAMEPROJECTFILE =/media/data/Unreal Engine/Projects/obstacle-assault/ObstacleAssault 5.1/ObstacleAssault.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	ObstacleAssault-Linux-DebugGame  \
	ObstacleAssault-Linux-Shipping  \
	ObstacleAssault \
	ObstacleAssaultEditor-Linux-DebugGame  \
	ObstacleAssaultEditor-Linux-Shipping  \
	ObstacleAssaultEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ObstacleAssaultEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ObstacleAssaultEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

ObstacleAssault-Linux-DebugGame:
	 $(PROJECTBUILD) ObstacleAssault Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ObstacleAssault-Linux-Shipping:
	 $(PROJECTBUILD) ObstacleAssault Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ObstacleAssault:
	 $(PROJECTBUILD) ObstacleAssault Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ObstacleAssaultEditor-Linux-DebugGame:
	 $(PROJECTBUILD) ObstacleAssaultEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ObstacleAssaultEditor-Linux-Shipping:
	 $(PROJECTBUILD) ObstacleAssaultEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ObstacleAssaultEditor:
	 $(PROJECTBUILD) ObstacleAssaultEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
